# Python Modules

## 1. Pandas

In [ ]:
## What is Pandas?

# Pandas is a Python library used for working with data

#It helps you:
#        Read data
#        Analyze data
#        Clean data
#        Modify data
#        Save data

In [ ]:
## Why Use Pandas?

## Without Pandas

# Imagine finding:

# Average salary
# Highest marks
# Students older than 20

## Using normal Python would require many loops

## With Pandas -> Much easier

df["marks"].mean()
df["marks"].max()
df[df["Age"]>20]

### Install Pandas

In [1]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\World\AppData\Roaming\Python\Python314\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\World\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\World\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\World\AppData\Roaming\Python\Python314\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\World\AppData\Roaming\Python\Python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\World\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Import Pandas

In [ ]:
import pandas as pd

## Why pd? -> Just a shortcut

## Instead of writing -> pandas.DataFrame()
pandas.DataFrame()

## we write -> pd.DataFrame()
pd.DataFrame()

### Check Version

In [2]:
import pandas as pd

print(pd.__version__)

2.3.3

### Series

In [3]:
# A Series is one column -> only one column

# Series – A one-dimensional labeled array
import pandas as pd

s = pd.Series([10, 20, 30])
print(s)

## In Output -> 0,1,2 are indexes

0    10
1    20
2    30
dtype: int64

### Access Value

In [4]:
s = pd.Series([10, 20, 30])
print(s[0])

10

### Custom Index

In [5]:
## Custom Index

# Instead of numbers, -> give names

a = [12,23,45]
s = pd.Series(a,index=["A","B","C"])
print(s)

A    12
B    23
C    45
dtype: int64

### Access

In [6]:
print(s["B"])

23

### Series from Dictionary

In [7]:
## Dictionary

marks = {
    "Ali" : 90,
    "Alisha" : 100
}

## Convert to Series

s = pd.Series(marks)
print(s)

# Dictionary keys become indexes

Ali        90
Alisha    100
dtype: int64

In [8]:
## Select Specific Keys

s1 = pd.Series(marks,index=["Ali"])
print(s1)

Ali    90
dtype: int64

## DataFrame

In [9]:
# DataFrame – A two-dimensional table with rows and columns
## A DataFrame is a complete table

import pandas as pd

## Create DataFrame
data = {
    "Name": ["Alisha", "Ali", "Zarmeen"],
    "Age": [25, 30, 20],
    "City": ["Lahore", "Sahiwal", "Multan"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age     City
0   Alisha   25   Lahore
1      Ali   30  Sahiwal
2  Zarmeen   20   Multan

### DataFrame from Dictionary

In [10]:
## DataFrame from Dictionary

data = {
    "Calories" : [420,340,201],
    "Duration": [40,50,45]
}

df = pd.DataFrame(data)
print(df)

## Each key becomes a column

   Calories  Duration
0       420        40
1       340        50
2       201        45

### loc[]

In [11]:
## loc[]

## Used to access rows

print(df.loc[0]) # one row in output

Calories    420
Duration     40
Name: 0, dtype: int64

In [12]:
## Multiple Rows

print(df.loc[[0,1]])

## Notice the double brackets [[ ]] because ->  passing a list of row indexes

   Calories  Duration
0       420        40
1       340        50

Named Index

In [13]:
data = {
    "Calories" : [420,340,201],
    "Duration": [40,50,45]
}

df = pd.DataFrame(data,index=["day1","day2","day3"])
print(df)

      Calories  Duration
day1       420        40
day2       340        50
day3       201        45

Access

In [14]:
print(df.loc["day2"])

Calories    340
Duration     50
Name: day2, dtype: int64

## Read CSV

In [19]:
## Read CSV

# CSV = Comma Separated Values

## Load 
df = pd.read_csv("student1.csv")

## Now the CSV becomes a DataFrame

#Print
print(df)

   Student_ID     Name   Age  Gender               Department  Semester  CGPA  \
0   0         101   Tayyab  20.0    Male         C...
1   1         102     Zari  21.0  Female     Softw...
2   2         103    Ahmed   NaN    Male         C...
3   3         104  Ibrahim  22.0    Male          ...
4   4         105   Kainat  20.0  Female         C...
5   5         106   Sajjad  21.0    Male     Softw...
6   6         107  Unknown  23.0    Male  Artifici...
7   7         108     DevX  20.0  Female         C...
8   8         109      NaN  22.0  Female  Artifici...
9   9         110    Ahmed  21.0    Male     Softw...
10                          City  Attendance  Marks
11                 0      Lahore        90.0   85.0
12                 1     Karachi        95.0   91.0
13                 2   Islamabad        88.0   76.0
14                 3      Lahore         NaN   89.0
15                 4  Faisalabad        82.0   72.0
16                 5     Karachi        97.0    NaN
17                 6      Multan        70.0    NaN
18                 7      Lahore        91.0   87.0
19                 8   Islamabad        85.0   80.0
20                 9      Lahore        89.0   78.0

In [20]:
## Entire Table

print(df.to_string())

## Without to_string(), Pandas may show only the first and last few rows for large datasets

       Student_ID     Name   Age  Gender               Department  Semester  CGPA  \
0   0         101   Tayyab  20.0    Male         Computer Science         4  3.45
1   1         102     Zari  21.0  Female     Software Engineering         5  3.80
2   2         103    Ahmed   NaN    Male         Computer Science         4  2.95
3   3         104  Ibrahim  22.0    Male             Data Science         6  3.65
4   4         105   Kainat  20.0  Female         Computer Science         4   NaN
5   5         106   Sajjad  21.0    Male     Software Engineering         5  3.90
6   6         107  Unknown  23.0    Male  Artificial Intelligence         7  2.80
7   7         108     DevX  20.0  Female         Computer Science         4  3.50
8   8         109      NaN  22.0  Female  Artificial Intelligence         6  3.10
9   9         110    Ahmed  21.0    Male     Software Engineering         5  3.20
10                                                         City  Attendance  Marks
11                                                0      Lahore        90.0   85.0
12                                                1     Karachi        95.0   91.0
13                                                2   Islamabad        88.0   76.0
14                                                3      Lahore         NaN   89.0
15                                                4  Faisalabad        82.0   72.0
16                                                5     Karachi        97.0    NaN
17                                                6      Multan        70.0    NaN
18                                                7      Lahore        91.0   87.0
19                                                8   Islamabad        85.0   80.0
20                                                9      Lahore        89.0   78.0

In [25]:
## or directly from a dictionary

students = {
"Name":["Ali","ALisha"],
"Age":[20,21]
}

df = pd.DataFrame(students)
print(df)

     Name  Age
0     Ali   20
1  ALisha   21

Common Pandas Operations

In [27]:
# Read Dataset

import pandas as pd

df = pd.read_csv("student1.csv")
print(df)

   Student_ID     Name   Age  Gender               Department  Semester  CGPA  \
0   0         101   Tayyab  20.0    Male         C...
1   1         102     Zari  21.0  Female     Softw...
2   2         103    Ahmed   NaN    Male         C...
3   3         104  Ibrahim  22.0    Male          ...
4   4         105   Kainat  20.0  Female         C...
5   5         106   Sajjad  21.0    Male     Softw...
6   6         107  Unknown  23.0    Male  Artifici...
7   7         108     DevX  20.0  Female         C...
8   8         109      NaN  22.0  Female  Artifici...
9   9         110    Ahmed  21.0    Male     Softw...
10                          City  Attendance  Marks
11                 0      Lahore        90.0   85.0
12                 1     Karachi        95.0   91.0
13                 2   Islamabad        88.0   76.0
14                 3      Lahore         NaN   89.0
15                 4  Faisalabad        82.0   72.0
16                 5     Karachi        97.0    NaN
17                 6      Multan        70.0    NaN
18                 7      Lahore        91.0   87.0
19                 8   Islamabad        85.0   80.0
20                 9      Lahore        89.0   78.0

Pandas - Analyzing DataFrames

head()

In [28]:
## Shows first rows
#Default First 5 rows
df.head()

,Student_ID Name Age Gender Department Semester CGPA \
0,0 101 Tayyab 20.0 Male C...
1,1 102 Zari 21.0 Female Softw...
2,2 103 Ahmed NaN Male C...
3,3 104 Ibrahim 22.0 Male ...
4,4 105 Kainat 20.0 Female C...

Specific rows

In [29]:
#First 10 rows
df.head(10)

,Student_ID Name Age Gender Department Semester CGPA \
0,0 101 Tayyab 20.0 Male C...
1,1 102 Zari 21.0 Female Softw...
2,2 103 Ahmed NaN Male C...
3,3 104 Ibrahim 22.0 Male ...
4,4 105 Kainat 20.0 Female C...
5,5 106 Sajjad 21.0 Male Softw...
6,6 107 Unknown 23.0 Male Artifici...
7,7 108 DevX 20.0 Female C...
8,8 109 NaN 22.0 Female Artifici...
9,9 110 Ahmed 21.0 Male Softw...

tail()

In [30]:
#Shows Last Rows
df.tail()
## Default last 5 rows

,Student_ID Name Age Gender Department Semester CGPA \
16,5 Karachi 97.0 NaN
17,6 Multan 70.0 NaN
18,7 Lahore 91.0 87.0
19,8 Islamabad 85.0 80.0
20,9 Lahore 89.0 78.0

info()

In [31]:
# Dataset Information
df.info()

## It tells:
# -> Number of rows
# -> Number of columns
# -> Column names
# -> Data types
# -> Null values
# -> Memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 1 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0      Student_ID     Name   Age  Gender               Department  Semester  CGPA  \  21 non-null     object
dtypes: object(1)
memory usage: 300.0+ bytes

In [32]:
#Shape
df.shape

(21, 1)

In [33]:
#Columns
df.columns

Index(['   Student_ID     Name   Age  Gender               Department  Semester  CGPA  \'], dtype='object')

In [34]:
# Data Types
df.dtypes

Student_ID     Name   Age  Gender               Department  Semester  CGPA  \    object
dtype: object

In [35]:
# Statistical Summary
df.describe()

,Student_ID Name Age Gender Department Semester CGPA \
count,21
unique,21
top,0 101 Tayyab 20.0 Male C...
freq,1

NULL Values

In [36]:
## Null Values 

# NULL -> means -> No data

## Example

#Name	  Marks
# Ali	   90
# Ahmed	   NULL
# Alisha   80

## Ahmed's marks are missing

# Pandas shows this in info() so -> know the dataset may need cleaning

Data Cleaning

In [37]:
# Missing Values
df.isnull()

,Student_ID Name Age Gender Department Semester CGPA \
0,False
1,False
2,False
3,False
4,False
5,False
6,False
7,False
8,False
9,False
10,False
11,False
12,False
13,False
14,False
15,False
16,False
17,False
18,False
19,False
20,False

In [38]:
df.isnull().sum()

Student_ID     Name   Age  Gender               Department  Semester  CGPA  \    0
dtype: int64

In [ ]:
#FIll Missing Values
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [40]:
df.isnull().sum()

Student_ID     Name   Age  Gender               Department  Semester  CGPA  \    0
dtype: int64

In [41]:
print(df)

   Student_ID     Name   Age  Gender               Department  Semester  CGPA  \
0   0         101   Tayyab  20.0    Male         C...
1   1         102     Zari  21.0  Female     Softw...
2   2         103    Ahmed   NaN    Male         C...
3   3         104  Ibrahim  22.0    Male          ...
4   4         105   Kainat  20.0  Female         C...
5   5         106   Sajjad  21.0    Male     Softw...
6   6         107  Unknown  23.0    Male  Artifici...
7   7         108     DevX  20.0  Female         C...
8   8         109      NaN  22.0  Female  Artifici...
9   9         110    Ahmed  21.0    Male     Softw...
10                          City  Attendance  Marks
11                 0      Lahore        90.0   85.0
12                 1     Karachi        95.0   91.0
13                 2   Islamabad        88.0   76.0
14                 3      Lahore         NaN   89.0
15                 4  Faisalabad        82.0   72.0
16                 5     Karachi        97.0    NaN
17                 6      Multan        70.0    NaN
18                 7      Lahore        91.0   87.0
19                 8   Islamabad        85.0   80.0
20                 9      Lahore        89.0   78.0

In [ ]:
#Selecting Data
df["Name"]

In [ ]:
#Selecting Data
df["Name"]