## EDA
Exploratory Data Analysis 
      or 
Data wrangling

 EDA is the crucial first step in data science used to understand a dataset's structure, uncover patterns, detect anomalies, and check assumptions using statistical summaries and graphical representations. 

EDA means explore data on basis on Analysis 

technique used to fetch insights from data

In [ ]:
## import libraries 

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

Steps of EDA Analysis

1. imprt dataset

In [39]:
## import data 
df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

2. Bigger picture 
Unerstanding data

we should know data types (df.dtypes)   ## column heading are varaiables 

## output: Type of varaiable 

## int64 -> numeric
## float -> numeric include decimal
## object -> double quality (categorical)
## class -> category -> first, second, third
## boolean -> true , false
## string -> text

In [41]:

## Bigger picture 
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

information

In [ ]:
df.info()
## dataset information total no of rows and columns it has 891 rows and 15 columns 

## values less than 891 means missing or null values 

## Information which is very important -> RangeIndex: 891 entries, 0 to 890

## 3   age          714 non-null    float64 -> 891 - 714 = 177 -> Null Value (missing value)

## 11  deck         203 non-null    category -> 891 - 203 = 688 -> Null Value (missing value)

##  One step is to count missing values, or null values or NaN values

## Find Missing values is a common part of data analysis

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

Count Missing/ Null Values

In [ ]:
df.isnull().sum()  ## finding missiing and null values

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

copy data of df in df2 
 df2 = df #44:00 min -> https://www.youtube.com/watch?v=sCdu54Mq0FA&list=PL9XvIvvVL50Fba7psesg6ynQXdipw-yoN

In [ ]:
## df2

Percentage of null values

In [ ]:
df.isnull().sum()*100/len(df)

### if any column value is more than 70 or 75 percent then that column value is meaningless
# we can remove that column 

## and columns of values  0.2 or 0.3 percent we can remove that rows

# missing_Percentage = df.isnull().mean()*100 # another method to find percentage of missing values

# There are some rules in the world of data science, like every field has some rules, if this happen then this will happen 

## E.g -> deck           77.216611
## A rule which is in science -> if the value of a column is more than 70% or more than 75% -> that column become useless for your data -> or importing it or extracting anything else becomes useless -> but it depends on scenario

## It is a general rule 

## if you have this, it may contain any important information

## But usually what happen -> remove this column -> not bring it inside your data

## Usually -> more missing values column -> have important values also based on difference  

## E.g -> embarked        0.224467, embark_town     0.224467

# two,three,four missing  -> remove rows -> there are very few instances which are bad rows -> not remove this column 

# remove the entire row if data is not  fully impacted -> means not damaged


## E.g -> age            19.865320

# 19% missing values -> numeric values -> 3 to 4 methods to impute it -> impute -> wherever this missing values -> replace with the average of age column, or -> replace with median of age , or -> or replace with mode if it is categorical variable


## When approximately 30-40% of the data is missing -> then we try to impute 

## age good factor ahead -> they are dependent on each other

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

How to deal with missing values in EDA Analysis 
categorical/object , Numeric , Boolean ,

1. Numerical Data(Int,float)
Replace different values of numerical variable  
it is float number we can impute it with 3 to 4 methods
where missing value is in age we will replace it with average of age  OR mean
Method 1: Fill with Mean (Best for normally distributed data)
Method 2: Fill with Median   (Recommended for Skewed Data)
Method 3: Fill with Constant (0,-1)
Method 4: Interpolation


2. Categorical Data
Method 1 :Replace it with mode of age  
Method 2 :Fill or replace with unknown
Method 3 :Forward fill(ffill)
Method 4 :Backward fill(bfill)


3. Boolean Data

Method 1:Replace missing values with true  

Method 2:Replace missing values with false

Method 3:Replace missing values with mode 

4. Forward Fill (ffill)

Missing values filled from prevous row 

Synatx: df.ffill()

5. Backward Fill (Bfill)

Missing values Filled from next row

SYNATX: df.bfill()

6. Drop Missing Values 

if we have many missing values then remove only rows 

SYNTAX: df.dropna()

7. Fill Entire DataFrame 

Fill numeric columns only 

SYNTAX: df = df.fillna(df.mean(numeric_only=True))

we canot replace categorical data  if we do we will get incorrect answers and we have to do extra calculations

In [ ]:
## FILL NUMERIC
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Fare"] = df["Fare"].fillna(df["Fare"].mean())

In [ ]:
## FILL CATEGORICAL 
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

df["Sex"] = df["Sex"].fillna(df["Sex"].mode()[0])

## NAN (NOT A NUMBER)

NaN values in the dataset should be identified separately and replaced with appropriate values.

we replace a numeric variable with mean  because it is at least in the range

In [ ]:
df['age'].unique()   ## Unique Values of age column

array([22.        , 38.        , 26.        , 35.        , 29.69911765,
       54.        ,  2.        , 27.        , 14.        ,  4.        ,
       58.        , 20.        , 39.        , 55.        , 31.        ,
       34.        , 15.        , 28.        ,  8.        , 19.        ,
       40.        , 66.        , 42.        , 21.        , 18.        ,
        3.        ,  7.        , 49.        , 29.        , 65.        ,
       28.5       ,  5.        , 11.        , 45.        , 17.        ,
       32.        , 16.        , 25.        ,  0.83      , 30.        ,
       33.        , 23.        , 24.        , 46.        , 59.        ,
       71.        , 37.        , 47.        , 14.5       , 70.5       ,
       32.5       , 12.        ,  9.        , 36.5       , 51.        ,
       55.5       , 40.5       , 44.        ,  1.        , 61.        ,
       56.        , 50.        , 36.        , 45.5       , 20.5       ,
       62.        , 41.        , 52.        , 63.        , 23.5       ,
        0.92      , 43.        , 60.        , 10.        , 64.        ,
       13.        , 48.        ,  0.75      , 53.        , 57.        ,
       80.        , 70.        , 24.5       ,  6.        ,  0.67      ,
       30.5       ,  0.42      , 34.5       , 74.        ])

In [36]:
df['age'].max()## maximum age in age column
df['age'].min()## minimum 
df['age'].mean()  ## mean 
## without print will show only last function value

## with it will show each value
print(df['age'].max())## maximum age in age column
print(df['age'].min())## minimum 
print(df['age'].mean())

80.0
0.42
29.69911764705882

## 1.Replace nan with mean

create a new dataframe

In [45]:
df2=df['age'].fillna(df['age'].mean())
df2

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [46]:
df2.isnull().sum()  ## calculate null values

np.int64(0)

In [47]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [51]:
df['age'].fillna(df['age'].mean(), inplace=True) #now this syntax is not recommended in pandas version
## Updated Original Dataset by adding a -> inplace = True
df2

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [53]:
df.fillna({"age": df["age"].mean()}, inplace=True) # use this syntax
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df2=df  ## copy df in df2

In [55]:
df2.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [56]:
df2.isnull().sum()*100/len(df2)

survived        0.000000
pclass          0.000000
sex             0.000000
age             0.000000
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [57]:
print(df2['age'].min())
print(df2['age'].max())
print(df2['age'].mean())

0.42
80.0
29.69911764705882

In [58]:
df2['age'].unique()

array([22.        , 38.        , 26.        , 35.        , 29.69911765,
       54.        ,  2.        , 27.        , 14.        ,  4.        ,
       58.        , 20.        , 39.        , 55.        , 31.        ,
       34.        , 15.        , 28.        ,  8.        , 19.        ,
       40.        , 66.        , 42.        , 21.        , 18.        ,
        3.        ,  7.        , 49.        , 29.        , 65.        ,
       28.5       ,  5.        , 11.        , 45.        , 17.        ,
       32.        , 16.        , 25.        ,  0.83      , 30.        ,
       33.        , 23.        , 24.        , 46.        , 59.        ,
       71.        , 37.        , 47.        , 14.5       , 70.5       ,
       32.5       , 12.        ,  9.        , 36.5       , 51.        ,
       55.5       , 40.5       , 44.        ,  1.        , 61.        ,
       56.        , 50.        , 36.        , 45.5       , 20.5       ,
       62.        , 41.        , 52.        , 63.        , 23.5       ,
        0.92      , 43.        , 60.        , 10.        , 64.        ,
       13.        , 48.        ,  0.75      , 53.        , 57.        ,
       80.        , 70.        , 24.5       ,  6.        ,  0.67      ,
       30.5       ,  0.42      , 34.5       , 74.        ])

In [60]:
df2.fillna({"age": df2["age"].mean()}, inplace=True)
df2

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [62]:
df3 = df2
df3.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df3 = df3.drop(columns=["deck"])   ## deck column has removed 
df3

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [64]:
df3.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [68]:
df4 = df3
df4.fillna({"embark_town": df4["embark_town"].mode()[0]}, inplace=True)
## embark_town -> categories replace with mode
df4
df4.fillna({"embarked": df4["embarked"].mode()[0]}, inplace=True)
df4

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [74]:
df4.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

## Mean, Median, Mode

Mean: The average. Add all numbers together, then divide by the total count

Median: The middle number. Order the numbers from smallest to largest and pick the exact middle
2,3,5,7 -> center 3,5 -> average of center -> 3+5/2 = 4 -> median = 4

Mode: The most frequent number. The number that appears the most times in a data set
2,3,5,6,6,9,10,9 -> mode -> (6,9) -> (first mode, second mode) -> (index 0 , index 1)
in code -> mode()[0] -> [0] -> means first mode which is 6

# Data wrangling:

Data wrangling also known as data munging, is the essential process of transforming and mapping raw, messy data into a structured and valuable format ready for analytics

 Both Data Wrangling and Exploratory data analysis are running simultaneously

Exploratory data analysis -> exploring data -> exploring means how many missing values are there 

Wrangle -> how to deal with this(missing values)

EDA = "What is wrong with my data?"
Data Wrangling = "How do I fix my data?"

## EDA (Explore)	        Data Wrangling (Clean)
Problem identify 	          Problem solve 
Missing values count 	      Missing values fill/drop 
Duplicates check 	          Duplicates remove 
Outliers detect 	          Outliers treat/remove 
Data Understanding	          Data Prepare for model

In [69]:
print("mean = ", df["age"].mean())
print("median = ", df["age"].median())
print("mode = ", df["age"].mode())

## mean and median -> near each other

mean =  29.69911764705882
median =  29.69911764705882
mode =  0    29.699118
Name: age, dtype: float64

In [76]:
print("mode =", df["embark_town"].mode())

mode = 0    Southampton
Name: embark_town, dtype: object

In [78]:
print("mode =", df["embarked"].mode())

mode = 0    S
Name: embarked, dtype: object

## Two techniques Learn 

1. How to explore Data
2. How to Deal with it

In [73]:
df
# 1 row -> 1 person Data
# 0	0	3	male	22.000000	1	0	7.2500	S	Third	man	True	NaN	Southampton	no	False

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## 14 variables 
13 variables data exist -> one is missing
Impute missing one on the basis of other 13 variables 
if you can impute it -> this is called machine learning
for example impute age on basis of other 13 variables is machine learning 

Data is also imputed on the basis of all the other variable interaction -> called machine learning imputation model

## Steps: Data Wrangling 

1. Import Libraries

2. Import Dataset

3. Explore your data
Information
Datatypes
Missing Values
Take Sense of your data

4. Understanding all the variables

5. Relationship between the Variables(Heatmap,Pairplot, Correlation)

6. Brainstorming ->  which way we can take data forward
Normalize -> a technique by which data or things are brought in similar units, they come closer to each other -> so that we can compare properly
Normalize things to compare with each other, and bring to closer so that the data becomes easy
Removing Outliers  -> something coming from outside or which does not belong to the data  

7. Tidy data, Clean data
80% of the time we do these things 

8. Ready for Statistical Analysis

9. Ready for Prediction

10. Ready for Machine Learning

11. Ready for Deep Learning

20% of the time we do these things

## Rule   world of data science

if we have 100 of data science work  at least 80 hours of your data spend on data cleaning, data wrangling

## Normalization Techniques

1. Min-Max Scaling
2. Standardization (Z-Score Scaling)
3. Robust Scaling
4. Max Absolute Scaling
5. Unit Vector Scaling (L1/L2 Normalization)

## Outlier Detection & Removal Techniques

## Detection Techniques
1. Box Plot
2. Scatter Plot
3. Histogram
4. IQR (Interquartile Range) Method ->  Most Common
5. Z-Score Method
6. Modified Z-Score
7. Percentile Method
8. Isolation Forest (Machine Learning)
9. Local Outlier Factor (LOF) (Machine Learning)
10. DBSCAN (Clustering-based)


## Outlier Handling Techniques

1. Remove Outliers -> Delete rows containing outliers
2. Capping / Winsorization -> Replace extreme values with upper/lower limits
3. Transformation
Log Transformation
Square Root Transformation
Box-Cox Transformation
Yeo-Johnson Transformation
Replace with Mean/Median -> In some cases, replace extreme values instead of removing them
Use Robust Models -> Use algorithms less sensitive to outliers (e.g., tree-based models)